### ISSUE TITLE
Neo GUI- funds transfered to watch only address

### ISSUE THREAD

**Issue by MashiRod** [neo-project/neo#154] opened 2018-01-23 20:37 UTC
I used the Neo-GUI to make a Neo transfer from my wallet to my Bittrex account. However, the amount I tranfered was credited on my Bittrex account without problems BUT the balance of my Neos on the wallet were sent to a new wallet address and appears now as "watch only address" in the Neo-GUI!

How can please help to get access to the Neos on the "watch only address" wallet.

**Comment by erikzhang** [comment] 2018-01-24 00:41
Duplicate of neo-project/neo-gui#165

**Closed by erikzhang** 2018-01-24 00:41 UTC
Labels: duplicate
