### ISSUE TITLE
After dBFT 2.0, block time gets longer,why so?

### ISSUE THREAD

**Issue by i359** [neo-project/neo#799] opened 2019-06-06 11:13 UTC
trading volume is small,  but block time gets longer, the average is more than 20 seconds. What happened?

**Comment by i359** [comment] 2019-06-06 12:02
![111](https://user-images.githubusercontent.com/43022140/59031310-eda48e80-8895-11e9-9f60-5c8e4ef84517.JPG)

**Comment by i359** [comment] 2019-06-06 12:23
![111](https://user-images.githubusercontent.com/43022140/59032444-e5018780-8898-11e9-959d-b9c9b738112b.JPG)

**Comment by igormcoelho** [comment] 2019-06-06 12:53
@vncoelho what do you think?

I guess this is the same average time that testnet has been showing in past months as well, so it's not surprising for me. To know the precise causes, it's necessary catch all consensus messages and see step by step the network progressing. In my opinion, it was expected to have higher times, as another layer was introduced, and delays can be huge in a global network (even with not much messages exchanged). The focus of dBFT 2.0 was two things hard to achieve: guarantee block finality in a definitive manner; and to provide greater stability to the network. Achieving a fixed 15 seconds average can also be done, in the future, as it has never been the focus of the last months of research and development.

**Comment by vncoelho** [comment] 2019-06-06 13:36
I agree.
But I believe that this printscreen refers to a specific time frame.
For example, in the day of the implementation, block times were lower, on a average of 16-17s.

The network is decentralized and CN are spread around the globe. There is also a global delay influence if we analyze specific time windows.

**Comment by vncoelho** [comment] 2019-06-06 17:04
I will close this issue because I believe that the question is answered.

With a detailed statistical analyses we could extend the discussion.

Thanks for wondering and investigating this @i359.
Fell free to keep the discussion and open any future issue or question.

**Comment by jsolman** [comment] 2019-06-06 19:49
Those times are based on times in the block headers also, not necessarily actual wall clock times between blocks.

**Comment by jsolman** [comment] 2019-06-06 19:53
However, if they are consistently longer it is likely network latency along with the additional commit phase. The important thing is that the block times are stable and the graph of maximum block times is much lower on average.

**Comment by PBSJ** [comment] 2019-06-06 23:53
But are they stable? They seem to be consistently creeping higher. I think this warrants monitoring.

**Comment by jsolman** [comment] 2019-06-07 03:29
It needs to be examined to find the root cause.

**Comment by sector420** [comment] 2019-06-13 18:07
This seems to be happening again.

**Comment by igormcoelho** [comment] 2019-06-16 17:23
Looks like it's not an issue in dbft 2.0 afterall... it can work just fine, see it right now (average slightly over 16 seconds):
![image](https://user-images.githubusercontent.com/290989/59567297-42889780-9042-11e9-8552-fd6e469721fb.png)

The other issue does not seem to be dbft-related, but more like p2p related.

**Comment by vncoelho** [comment] 2019-06-16 17:47
True, brother, lets focus on discussion on #803.

**Closed** 2019-07-22 17:14 UTC
Labels: question
