### ISSUE TITLE
Nex tokens disappeared from Neon wallet after transaction and no transaction history

### ISSUE THREAD

**Issue by someonelikespirit** [neo-project/neo#577] opened 2019-01-29 08:14 UTC
I make today (29.01.2019 time was about 9:00-9:15 UTC+2) transaction of 800 nex tokens from wallet AaxZKGgQkDdES6Zo42rbUkfuhaxcZuF9z6 to wallet
APn7yScYvEVfXyLyWmG87bu2n7abXLzNwf,  transaction was made in neon app, but after i make it there is no transaction history of this transaction, and mine tokens disappeared from wallet AaxZKGgQkDdES6Zo42rbUkfuhaxcZuF9z6  and didnt come to wallet APn7yScYvEVfXyLyWmG87bu2n7abXLzNwf  ,,, What i have to do? help me please!

**Comment by canesin** [comment] 2019-01-29 11:31
@someonelikespirit the neoscan explorer is out of sync because of a issue that happened in the network this early morning, the network continues to work but explorers are all stuck. Your transaction should appear as soon as neoscan is recovered.

The issue that happened is known for a long time and @erikzhang is working to accept the contributions that fix this for some time also. So a proper fix release should be eminent.

**Comment by jsolman** [comment] 2019-02-21 10:00
@canesin is referring to consensus improvements that will prevent forked blocks through the added commit phase. Then Neo nodes and explorers that depend on them like neoscan.io will not become stuck for that reason. You can follow #547 as it is the prevailing PR that contains the improvements that fix the forked block issue.

Since we are calling the stuck block the root cause of this issue it is fixed by #547.

**Comment by jsolman** [comment] 2019-03-07 03:08
Root cause fix has been merged. Lets close this issue when 2.10.0 is deployed to MainNet CN nodes.

**Comment by vncoelho** [comment] 2019-04-09 16:36
Miss clicked here. This button should have a warning...aheuahuea
We believe that soon it will be patched on Mainnet.

**Comment by vncoelho** [comment] 2019-06-03 14:11
dBFT 2.0 has been successfully deployed into MainNet CN!
A great achievement to the scientific literature and also to the NEO ecosystem.

**Closed by vncoelho** 2019-06-03 14:11 UTC
Labels: help wanted
