### ISSUE TITLE
English README

### ISSUE THREAD

**Issue by ralphtheninja** [neo-project/neo#49] opened 2017-08-13 21:35 UTC
Hi! A suggestion would be to have the readme in english. I know a lot of people speak chinese but if you want to reach out beyond china it can be difficult. You could also consider having two readmes, one in chinese and one in english.

**Comment by erikzhang** [comment] 2017-08-14 15:02
I agree. It will be done soon.

**Comment by erikzhang** [comment] 2017-08-15 11:02
Duplicate of #47

**Comment by felipeclopes** [comment] 2017-08-18 20:26
It is fixed already https://github.com/neo-project/neo/commit/dac1c84b774d53949391f305b1696ca049e87071

**Closed** 2017-08-19 09:02 UTC
Labels: duplicate
