### ISSUE TITLE
How can we run NEO Node(neo-cli) as deamon

### ISSUE THREAD

**Issue by rakeshiitd** [neo-project/neo#87] opened 2017-10-22 19:59 UTC
Hi.

In order to make RPC calls to neo node it is important for us to keep running a neo node in background so how can we achieve it with neo cli? I have tried it with tools like nohup and screen but can not make it. Please help me to run a node as deamon.

**Comment by erikzhang** [comment] 2017-10-23 05:09
Duplicate of https://github.com/neo-project/neo-cli/issues/48

**Closed by erikzhang** 2017-10-23 05:09 UTC
Labels: duplicate, invalid
