### ISSUE TITLE
Network spamming  - current fixes have not had the desired impact

### ISSUE THREAD

**Issue by bpetridis** [neo-project/neo#428] opened 2018-10-26 00:16 UTC
Hi All,

Raising this as an issue again as I don't believe the fixes mentioned in 

https://github.com/neo-project/neo/issues/353
and
https://github.com/neo-project/neo/issues/358

Have had the desired affect. Network is borderline unusable again with this latest spamming. My personal thought is that GAS should be mandated on all TX's as no matter how well the chain is tuned it's a hole I don't believe will ever be able to be fully plugged. I think this is beyond the point of conversation now and needs to be handled as a fully fledged outage incident.

However I have noticed that a lot of nodes are still lagging behind 2.9  - will that update once fully propagated address this? 

Please let us know,

Cheers

Bill

**Comment by JustinR1** [comment] 2018-10-26 00:29
I agree that there should be mandated gas fees on all txs.

**Comment by jibbah777** [comment] 2018-10-26 00:46
Cant there be a limit a user can send each block

**Comment by shargon** [comment] 2018-10-26 08:19
The NEO's difference is the free network, we can't lose it.

- We should increase the free TX size from 20 to 50
- We should add a little PoW for TX
- We should be able to remove TX from the pool, if it is a free TX and is waiting for more than X blocks (TBD)
- We should determine if is a free TX if his fee is > 0.0001, not 0.00000001

**Comment by erikzhang** [comment] 2018-10-26 08:45
> We should determine if is a free TX if his fee is > 0.0001, not 0.00000001

Fully agree with this.

**Comment by RavenXce** [comment] 2018-10-26 09:43
> The NEO's difference is the free network, we can't lose it.
> 
> * We should increase the free TX size from 20 to 50
> * We should add a little PoW for TX
> * We should be able to remove TX from the pool, if it is a free TX and is waiting for more than X blocks (TBD)
> * We should determine if is a free TX if his fee is > 0.0001, not 0.00000001

Strongly agree with all points! Especially the PoW idea.

> * We should determine if is a free TX if his fee is > 0.0001, not 0.00000001

But please make announcements before this happens so we can adjust our fee paying mechanism first!

**Comment by bpetridis** [comment] 2018-10-26 21:55
Out of curiosity how would the PoW model work in this scenario and what would it be measured against? Are talking more priority to nodes that contribute as opposed to clients that are simply invoking tons of TXs? Apologies if that sounds like a dumb question, just trying to wrap my head around it more.

**Comment by jsolman** [comment] 2018-10-27 01:39
How about .00001 min to not be considered free instead of .0001 ?

**Comment by RavenXce** [comment] 2018-10-27 05:03
> Out of curiosity how would the PoW model work in this scenario and what would it be measured against? Are we talking more priority to nodes that contribute as opposed to clients that are simply invoking tons of TXs? Apologies if that sounds like a dumb question, just trying to wrap my head around it more.

The transaction mining is already in discussion here: https://github.com/neo-project/neo/issues/408

For dropping of txs, there is an issue here (there are several other related iirc): https://github.com/neo-project/neo/issues/414

For the rest, there is no issue created yet afaik. This is the first time those have been proposed.

**Comment by Edgegasm** [comment] 2018-10-27 16:47
I think we'd go a long way in reducing these issues by:

1. Educating users on priority fees/simplifying the use of them (such as the way Neon v2 has done it)
2. Get exchanges to use fees when moving funds from a large number of wallets
3. Adding a small network fee for GAS claims

We can have free transactions, the problem is when too many free transactions occur all at once. Every time more than 20 free transactions are sent within 15 seconds, we end up bloating the mempool with transactions that *can* be processed but *aren't* because of the MaxFreeTransactionPerBlock limit. 

Adding a network fee to GAS claims has the added benefit of reducing the frequency of claims, and allows claims to go through during congested periods when lots of free transactions are competing for one of the 20 slots in a block. That will improve the UX a lot.

**Comment by bpetridis** [comment] 2018-10-28 00:09
> > Out of curiosity how would the PoW model work in this scenario and what would it be measured against? Are we talking more priority to nodes that contribute as opposed to clients that are simply invoking tons of TXs? Apologies if that sounds like a dumb question, just trying to wrap my head around it more.
> 
> The transaction mining is already in discussion here: #408
> 
> For dropping of txs, there is an issue here (there are several other related iirc): #414
> 
> For the rest, there is no issue created yet afaik. This is the first time those have been proposed.

Thanks for the links, the minor PoW idea sounds like a real winner. Just read through it, very smart.

**Comment by jibbah777** [comment] 2018-11-01 00:43
Implement auto-gas claim and/or only distribute when blocks are quiet and/,or limit gas claims to x amount per day dependant on network activity reducing the amount of transactions

**Comment by xenzorz** [comment] 2018-11-01 02:30
As others have mentioned the network is experiencing issues again.

My personal opinions:

- Gas claim reduced from 5mins to 30min
- Gas fee's on all Transactions, even 1 drop.

**Comment by shargon** [comment] 2018-11-01 10:46
@RavenXce https://github.com/neo-project/neo/pull/392 was merged, so now a low priority transaction will be like this

https://github.com/belane/neo/blob/7586f39db092bff5aa7bc0ff712f63fd7ca537ab/neo/Network/P2P/Payloads/Transaction.cs#L52

If the group is full, it will be cleaned, all the low priority TXs that have arrived from 20 blocks will be removed.

https://github.com/belane/neo/blob/7586f39db092bff5aa7bc0ff712f63fd7ca537ab/neo/Ledger/MemoryPool.cs#L108

**Comment by RavenXce** [comment] 2018-11-02 02:40
@shargon so the magic number to pay is 0.001 GAS?

**Comment by shargon** [comment] 2018-11-02 08:58
@RavenXce Yes, is 0.001 and is defined in `protocol.json`

**Comment by jsolman** [comment] 2018-11-05 08:39
@Tom-Chilli I have mentioned before the idea of having accounts throttled during situations where the mempool is large. Limiting to only one transaction for an address per block though is too simple and too limiting. I believe deriving the limit for transactions per block by an address as a function of the amount and age of the address’s gas

**Comment by jsolman** [comment] 2018-11-05 08:40
Sorry on mobile and accidentally; closed and reopened. The UI should ask to confirm instead of one click to close and comment.

**Comment by Tom-Chilli** [comment] 2018-11-05 09:01
Interesting concept, I do like the idea and very keen to see how it works! 

In the situation of sending more then one transactions per block per wallet, if someone wanted to send multiple transactions - do you see a gas cost as really that limiting? A drop of gas per transaction would allow thousands upon thousands of transactions for minimal cost. This would then push these transactions out of the 'free transaction limit' pool, and hopefully prevent congestion.

It seems to me the one of the main issues of congestion is to do with the free transactions, so every attempt to persuade people to utilise a gas fee would be beneficial?

**Comment by jsolman** [comment] 2019-01-12 02:50
This also can be closed by #500

**Closed** 2019-01-13 06:37 UTC
Labels: discussion
