### ISSUE TITLE
NEO are automatically transferred

### ISSUE THREAD

**Issue by luoshushua** [neo-project/neo#198] opened 2018-03-17 04:08 UTC
I created a wallet and got a new address (APiKPY1bwRMU1yuNVKvYKZVtxF8jv4w7Ai) by using neo-cli. Then, I transfered 1NEO to this address and received it successfully, but after a few minutes, this 1NEO has been transfered into an unknown address （ASnwQJTjhjYcFS7aJstzrZ5tFqho1AQHEJ）automatically. 
When I operated claim gas, GAS has been transfered into this address （ASnwQJTjhjYcFS7aJstzrZ5tFqho1AQHEJ）automatically too.
Could someone please tell me why would this happened? 

[https://neoscan.io/address/APiKPY1bwRMU1yuNVKvYKZVtxF8jv4w7Ai](url)

![image](https://user-images.githubusercontent.com/35419009/37551503-bb662786-29db-11e8-9b91-37ce0ad076b7.png)

**Comment by erikzhang** [comment] 2018-03-17 08:13
Duplicate of #178

**Closed** 2018-03-21 08:39 UTC
Labels: duplicate
