### ISSUE TITLE
Free Transaction limit not being fully utilized

### ISSUE THREAD

**Issue by saltyskip** [neo-project/neo#828] opened 2019-06-14 06:40 UTC
![image](https://user-images.githubusercontent.com/14796429/59488351-530e0600-8eba-11e9-9b7b-e51de1f72468.png)

Today around the block times posted above there were many free transactions going into the mempool. Due to simple policy limit only 20 max free transactions were allowed into the mempool which is expected behavior.

However there are many blocks in between that were not getting filled up to the 20 transaction limit. It would be expected that each block in this sequence would have 21 transactions until the mempool was cleared out. 

However at this time there were more than 100 transactions in the mempool

![image](https://user-images.githubusercontent.com/14796429/59488511-b6983380-8eba-11e9-9ef4-c7b28e35202b.png)

While several blocks only have 1 transaction in them

**Comment by igormcoelho** [comment] 2019-06-14 12:42
The issue is not the 20 free tx limit, which is being respected, the thing is that some consensus nodes are eventually not receiving these tx you have in your mempool. Remember that mempool is not the same in all nodes, and by some strange issue, eventually these empty blocks begin to happen (note that even high priority tx wouldn't get into these blocks too, so it's not a policy issue).

**Comment by vncoelho** [comment] 2019-06-14 13:56
@saltyskip, lets focus on #803.
Maybe close this one.

**Comment by shargon** [comment] 2019-06-14 14:02
Yes, the issue is #803

**Closed by shargon** 2019-06-14 14:02 UTC
