### ISSUE TITLE
私链共识后异常退出

### ISSUE THREAD

**Issue by syeerzy** [neo-project/neo#252] opened 2018-05-28 10:32 UTC
6台机器做共识,  高度已经由1变2,  然后过一会就纷纷抛出这个异常:

Unhandled Exception: System.ArgumentException: An item with the same key has already been added. Key: System.Threading.Tasks.Task`1[System.Threading.Tasks.VoidTaskResult]
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Neo.Network.LocalNode.<>c__DisplayClass61_0.<ConnectToPeersLoop>g__connectToPeers|0(IEnumerable`1 ipEndPoints)
   at Neo.Network.LocalNode.ConnectToPeersLoop()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
Aborted

看起来是添加了重复的task对象了

**Comment by erikzhang** [comment] 2018-05-28 11:13
Duplicate of neo-project/neo-cli#159

**Closed by erikzhang** 2018-05-28 11:13 UTC
Labels: bug, duplicate
