### ISSUE TITLE
How to properly filter an Enumerator? (onchain filter on stackitem Enumerator)

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#914] opened 2019-07-12 01:13 UTC
This appeared here: https://github.com/neo-project/neo/issues/877 and on NFT discussions, and many places else...

Suppose I have an Enumerator stack item:
```cs
Enumerator e = GetEnumerator();
```
How can I filter it? My first thought went back to OPEVAL discussions, but perhaps we need something less dangerous and already existing on neovm... delegates?
```cs
Enumerator e2 = e.Filter(x => hasProperty());
```

Could we pass this property to bool function as a delegate on C#? @lightszero @erikzhang @lock9 @shargon 

Perhaps this could generate something like:
`System.Enumerator.Filter  [parameter method position in code]`

example (draft):

```cs
delegate filterfunc(x) : int -> bool = x > 5; // don't know how to write it...

Enumerator e;
e.Filter(filterfunc);
// filterfunc is compiled to position 0001
```

`System.Enumerator.Filter  0001`

**Comment by igormcoelho** [comment] 2019-07-13 14:30
Agree with @shargon, json is very useful in.this context.

**Comment by lock9** [comment] 2019-07-15 18:23
Is this a duplicate of #880 ? Do you want to close this and continue only in #880 ?

**Comment by igormcoelho** [comment] 2019-12-06 19:03
@erikzhang I'll reopen this.

Now we can finally do it, using https://github.com/neo-project/neo-vm/issues/190

**Comment by erikzhang** [comment] 2019-12-07 02:36
No, you can't use it for data filtering. Because it cannot be passed to other contracts. So we need #284. That's why I close this.

**Closed by erikzhang** 2019-12-07 02:36 UTC
Labels: design, feature, vm
