### ISSUE TITLE
Since 4468502, no block has been generated in 25 minutes. what's happen？

### ISSUE THREAD

**Issue by i359** [neo-project/neo#1168] opened 2019-10-19 23:56 UTC
Since 4468502, no block has been generated in 25 minutes. what's happen?

**Comment by i359** [comment] 2019-10-20 00:18
![AAA](https://user-images.githubusercontent.com/43022140/67152922-0fb51f80-f312-11e9-9673-31f292228673.JPG)

**Comment by superboyiii** [comment] 2019-10-21 03:17
@i359 Mainnet automatically comes back later. Seems too many free txs made consensus nodes' mempool crowded which cause this delay.

**Comment by 35kus** [comment] 2019-10-22 03:16
I am wondering if this is an issue that has already been resolved in NEO3 or if the team is working towards a solution? I'm not a developer and just a member in the community, but it seems like it should be something that is relatively easy to avoid (and shouldn't occur so easily) by limiting the amount of transactions stored in the mempool - is that correct?

Was this caused by the YEZ airdrop?

**Comment by superboyiii** [comment] 2019-10-22 03:35
@35kus Yes, caused  by the YEZ airdrop which had full filled 20 limited free txs per block for 3 days.

**Comment by igormcoelho** [comment] 2019-11-05 13:06
In my opinion, Neo3 resolved this by adding a time-to-live on every transaction... Currently, this is limit is very high on Neo3 (I think 365 days), and I would expect something more reasonable such as few hours at most. This way, huge batches of tx like this should be properly coordinated, as tx would become invalid once expired (and need to be relaunched with different nonce). It's much fairer to general network, instead of pilling up thousands of free tx.

**Closed** 2019-12-06 07:10 UTC
Labels: bug
