### ISSUE TITLE
create contract address

### ISSUE THREAD

**Issue by yura-sutnuk** [neo-project/neo#275] opened 2018-06-21 15:10 UTC
I filled the form https://neo.org/Testnet/Create and requested several test NEO and GAS coin and now i need to create contract address but how do this?  On the official site i see only how make it in GUI but do not see any instruction how make it in CLI,  is GUI required for this?

**Comment by jonatanblockchain** [comment] 2018-06-22 09:55
Now, with neo-cli 2.7.6 you can create multisigaddress.

**Comment by erikzhang** [comment] 2018-06-25 07:07
Duplicate of #270

**Closed by erikzhang** 2018-06-25 07:07 UTC
Labels: duplicate
