### ISSUE TITLE
Proposal to increase the free fuel limit for contract execution

### ISSUE THREAD

**Issue by QingmingZi** [neo-project/neo#582] opened 2019-02-13 08:00 UTC
It is recommended to either increase the contract's free GAS quota or reduce the execution fee as soon as possible to avoid one functionality being split into two transactions to be executed.

Forced splitting of non-functional design causes the following problems:
1. A serious decline in user experience
2. The unnecessary dramatic growth of the transaction pool and the possible increase in the delayed confirmation of transactions. 
3. Significantly increase the complexity of contract development and reduce development friendliness.

With the continuous enrichment of NEO contract functionalities and the increasing complexity, the current free quota of 10 GAS has been seriously insufficient. For example, a CGAS transfer would consume 4.840 GAS. If you add some other functional logic, it is difficult to control the GAS consumption within 10GAS. Currently, in the community, there are many cases in which the logic is forced to be split because of the control of 10GAS.

It is recommended to increase the free quota to 20GAS or more, which will greatly increase the maximum complexity of free execution per transaction, facilitate complex logic, and enrich the NEO ecosystem.

**Comment by erikzhang** [comment] 2019-02-13 08:02
Duplicate of #286

**Comment by jsolman** [comment] 2019-02-13 12:50
And all that time devs spent optimizing to fit into the 10 gas becomes wasted. 😔

**Closed** 2019-05-13 14:43 UTC
Labels: duplicate
