### ISSUE TITLE
Not able to run NEO

### ISSUE THREAD

**Issue by khelle** [neo-project/neo#100] opened 2017-11-08 16:59 UTC
HI, I am not able to run NEO on Ubuntu 16.04. I have installed all dependencies and .NET, and when I try to start the program via:

**dotnet neo-cli.dll** 

I get following error:

```
Segmentation fault
```

Running **dotnet -d neo-cli.dll** gives me:

```
Telemetry is: Disabled
projectfactory: MSBUILD_EXE_PATH = /usr/share/dotnet/sdk/1.0.1/MSBuild.dll
projectfactory: MSBuild project path = 
projecttoolscommandresolver: ProjectFactory did not find Project.
Microsoft.DotNet.Cli.Utils.CommandUnknownException: No executable found matching command "dotnet-bin/release/netcoreapp1.0/neo-cli.dll"
   at Microsoft.DotNet.Cli.Utils.Command.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**dotnet --info** gives me:

```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.1
```

I tried several NEO versions, tried several .NET installations includning v1.* and v2.*, tried NEO ubuntu version ,portable version and compiling from source - nothing changes, the error is always the same.
 
There are already issues on this in neo-cli repository, few months old, but seems nobody is willing to help.

**Comment by erikzhang** [comment] 2017-11-09 02:53
Duplicate of https://github.com/neo-project/neo-cli/issues/42

**Closed** 2018-01-04 12:12 UTC
