### ISSUE TITLE
Exception handling for NeoContract

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#310] opened 2018-07-09 10:48 UTC
neo-project/neo-vm#192

**Comment by lock9** [comment] 2019-06-12 19:58
Hello Erik,
What is the expected behaviour when an exception occurs? I suppose that exception handling can be done in 'application' level only?

**Comment by lock9** [comment] 2019-06-13 06:01
Are we going to charge a fixed price for a rollback?
The user must send extra gas in order to pay for a rollback, if we don't consume it, we gave him back? 
If he doesn't have gas for the rollback, we don't do any rollback?
What are your ideas?
I don't know how the rollback will happen in practice, but I imagine that having a fixed price for the rollback is more reasonable (if rollbacks ever exist)

**Comment by erikzhang** [comment] 2019-06-13 09:13
What do you mean of "rollback"?

**Comment by lock9** [comment] 2019-06-17 00:32
Sorry, maybe I didn't understand what you meant.
What behaviour do you expect when an exception occurs?

**Comment by igormcoelho** [comment] 2019-06-17 02:51
This is a very expected feature for me too... don't you think it's better on NeoVM now, Erik?

Ricardo, from my perspective, I imagine something like this:

```
PUSH1
PUSH0
DIV
```
This would normally trigger a `FAULT` state, due to the zero division... but perhaps we could have predicted that with a "try" statement.
I've never seen how these things are implemented on high-level languages, or even on stack languages... it would be nice to see how MSIL does that, to have some good ideas ;)

Anyway, I imagine "something like this":
```
TRYJMP 0010 # jumps some bytes if something fails
PUSH1
PUSH0
DIV
PUSH2
PUSH3
ADD
CATCH  # finishes TRY behavior... a regular jump triggered when some commands fail.
```

Just a crazy guess here, never read anything about it ;)

**Comment by lock9** [comment] 2019-06-19 14:23
@igormcoelho  Do you think the user should pay a fixed fee for the exception handling or you think he should pay "per instruction"? 

Your design looks good. When an exception happens we pop 'everything' from the stack until we find the catch block?

**Comment by Tommo-L** [comment] 2020-04-14 13:19
Could help close issue, as try-catch pr has been merged.

**Closed** 2020-04-14 14:47 UTC
Labels: compiler, design, feature, vm
